# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govm < Formula
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/melkeydev/govm"
  version "0.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/Melkeydev/govm/releases/download/v0.0.1/govm_0.0.1_Darwin_all.tar.gz"
    sha256 "3db02e639a5fe767441ee4b236ce32857b5e6331f74fd6ac0eb1e70a5a3f494a"

    def install
      bin.install "govm"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Melkeydev/govm/releases/download/v0.0.1/govm_0.0.1_Linux_x86_64.tar.gz"
        sha256 "35b84282568b5787d13ddb296d069baa13e75341804de8e80ea4427d7051ccb4"

        def install
          bin.install "govm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Melkeydev/govm/releases/download/v0.0.1/govm_0.0.1_Linux_arm64.tar.gz"
        sha256 "a3a85a4f25ae00674ba975c79f1c9756e2845210ac9d9e13ca0cabcad300b046"

        def install
          bin.install "govm"
        end
      end
    end
  end
end
