# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govm < Formula
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/melkeydev/govm"
  version "0.0.2"
  license "MIT"

  on_macos do
    url "https://github.com/Melkeydev/govm/releases/download/v0.0.2/govm_0.0.2_Darwin_all.tar.gz"
    sha256 "7e1c995e7064869894e08a1bddf2dc85dc3131b1c4f10bc020aa43a8ca73e4e8"

    def install
      bin.install "govm"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Melkeydev/govm/releases/download/v0.0.2/govm_0.0.2_Linux_x86_64.tar.gz"
        sha256 "c39ac5cbfacbdd1ebcf821752e054a4cdc99fc76ec8271f7d0006acbe551fa9f"

        def install
          bin.install "govm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Melkeydev/govm/releases/download/v0.0.2/govm_0.0.2_Linux_arm64.tar.gz"
        sha256 "da0289b0fa19d888181f8644c5bae20e5c2eb6cf783805fde52e635d7381601e"

        def install
          bin.install "govm"
        end
      end
    end
  end
end
